[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  node_bundler = "esbuild"
  directory = ".output/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "20"
