/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthPrimeiroAcessoRouteImport } from './routes/_auth/primeiro-acesso'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminServicosRouteImport } from './routes/_authed/admin/servicos'
import { Route as AuthedAdminProdutosRouteImport } from './routes/_authed/admin/produtos'
import { Route as AuthedAdminPdvRouteImport } from './routes/_authed/admin/pdv'
import { Route as AuthedAdminFinanceiroRouteImport } from './routes/_authed/admin/financeiro'
import { Route as AuthedAdminEquipeRouteImport } from './routes/_authed/admin/equipe'
import { Route as AuthedAdminCrmRouteImport } from './routes/_authed/admin/crm'
import { Route as AuthedAdminClientesRouteImport } from './routes/_authed/admin/clientes'
import { Route as AuthedAdminAgendarNovoRouteImport } from './routes/_authed/admin/agendar-novo'
import { Route as AuthedAdminAgendamentosRouteImport } from './routes/_authed/admin/agendamentos'
import { Route as AuthedAdminAgendaRouteImport } from './routes/_authed/admin/agenda'
import { Route as AuthedAdminEquipeIndexRouteImport } from './routes/_authed/admin/equipe/index'
import { Route as AuthedAdminEquipeStaffIdHorariosRouteImport } from './routes/_authed/admin/equipe/$staffId/horarios'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPrimeiroAcessoRoute = AuthPrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminServicosRoute = AuthedAdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminProdutosRoute = AuthedAdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPdvRoute = AuthedAdminPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminFinanceiroRoute = AuthedAdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminEquipeRoute = AuthedAdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminCrmRoute = AuthedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminClientesRoute = AuthedAdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAgendarNovoRoute = AuthedAdminAgendarNovoRouteImport.update({
  id: '/agendar-novo',
  path: '/agendar-novo',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAgendamentosRoute = AuthedAdminAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAgendaRoute = AuthedAdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminEquipeIndexRoute = AuthedAdminEquipeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminEquipeRoute,
} as any)
const AuthedAdminEquipeStaffIdHorariosRoute =
  AuthedAdminEquipeStaffIdHorariosRouteImport.update({
    id: '/$staffId/horarios',
    path: '/$staffId/horarios',
    getParentRoute: () => AuthedAdminEquipeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/primeiro-acesso': typeof AuthPrimeiroAcessoRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/admin/agenda': typeof AuthedAdminAgendaRoute
  '/admin/agendamentos': typeof AuthedAdminAgendamentosRoute
  '/admin/agendar-novo': typeof AuthedAdminAgendarNovoRoute
  '/admin/clientes': typeof AuthedAdminClientesRoute
  '/admin/crm': typeof AuthedAdminCrmRoute
  '/admin/equipe': typeof AuthedAdminEquipeRouteWithChildren
  '/admin/financeiro': typeof AuthedAdminFinanceiroRoute
  '/admin/pdv': typeof AuthedAdminPdvRoute
  '/admin/produtos': typeof AuthedAdminProdutosRoute
  '/admin/servicos': typeof AuthedAdminServicosRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/admin/equipe/': typeof AuthedAdminEquipeIndexRoute
  '/admin/equipe/$staffId/horarios': typeof AuthedAdminEquipeStaffIdHorariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/primeiro-acesso': typeof AuthPrimeiroAcessoRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/admin/agenda': typeof AuthedAdminAgendaRoute
  '/admin/agendamentos': typeof AuthedAdminAgendamentosRoute
  '/admin/agendar-novo': typeof AuthedAdminAgendarNovoRoute
  '/admin/clientes': typeof AuthedAdminClientesRoute
  '/admin/crm': typeof AuthedAdminCrmRoute
  '/admin/financeiro': typeof AuthedAdminFinanceiroRoute
  '/admin/pdv': typeof AuthedAdminPdvRoute
  '/admin/produtos': typeof AuthedAdminProdutosRoute
  '/admin/servicos': typeof AuthedAdminServicosRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/admin/equipe': typeof AuthedAdminEquipeIndexRoute
  '/admin/equipe/$staffId/horarios': typeof AuthedAdminEquipeStaffIdHorariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/primeiro-acesso': typeof AuthPrimeiroAcessoRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_authed/admin/agenda': typeof AuthedAdminAgendaRoute
  '/_authed/admin/agendamentos': typeof AuthedAdminAgendamentosRoute
  '/_authed/admin/agendar-novo': typeof AuthedAdminAgendarNovoRoute
  '/_authed/admin/clientes': typeof AuthedAdminClientesRoute
  '/_authed/admin/crm': typeof AuthedAdminCrmRoute
  '/_authed/admin/equipe': typeof AuthedAdminEquipeRouteWithChildren
  '/_authed/admin/financeiro': typeof AuthedAdminFinanceiroRoute
  '/_authed/admin/pdv': typeof AuthedAdminPdvRoute
  '/_authed/admin/produtos': typeof AuthedAdminProdutosRoute
  '/_authed/admin/servicos': typeof AuthedAdminServicosRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/admin/equipe/': typeof AuthedAdminEquipeIndexRoute
  '/_authed/admin/equipe/$staffId/horarios': typeof AuthedAdminEquipeStaffIdHorariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/primeiro-acesso'
    | '/reset-password'
    | '/admin/agenda'
    | '/admin/agendamentos'
    | '/admin/agendar-novo'
    | '/admin/clientes'
    | '/admin/crm'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/pdv'
    | '/admin/produtos'
    | '/admin/servicos'
    | '/admin/'
    | '/admin/equipe/'
    | '/admin/equipe/$staffId/horarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/primeiro-acesso'
    | '/reset-password'
    | '/admin/agenda'
    | '/admin/agendamentos'
    | '/admin/agendar-novo'
    | '/admin/clientes'
    | '/admin/crm'
    | '/admin/financeiro'
    | '/admin/pdv'
    | '/admin/produtos'
    | '/admin/servicos'
    | '/admin'
    | '/admin/equipe'
    | '/admin/equipe/$staffId/horarios'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authed'
    | '/_authed/admin'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/primeiro-acesso'
    | '/_auth/reset-password'
    | '/_authed/admin/agenda'
    | '/_authed/admin/agendamentos'
    | '/_authed/admin/agendar-novo'
    | '/_authed/admin/clientes'
    | '/_authed/admin/crm'
    | '/_authed/admin/equipe'
    | '/_authed/admin/financeiro'
    | '/_authed/admin/pdv'
    | '/_authed/admin/produtos'
    | '/_authed/admin/servicos'
    | '/_authed/admin/'
    | '/_authed/admin/equipe/'
    | '/_authed/admin/equipe/$staffId/horarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/primeiro-acesso': {
      id: '/_auth/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof AuthPrimeiroAcessoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/servicos': {
      id: '/_authed/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AuthedAdminServicosRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/produtos': {
      id: '/_authed/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthedAdminProdutosRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/pdv': {
      id: '/_authed/admin/pdv'
      path: '/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AuthedAdminPdvRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/financeiro': {
      id: '/_authed/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthedAdminFinanceiroRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/equipe': {
      id: '/_authed/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthedAdminEquipeRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/crm': {
      id: '/_authed/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthedAdminCrmRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/clientes': {
      id: '/_authed/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthedAdminClientesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/agendar-novo': {
      id: '/_authed/admin/agendar-novo'
      path: '/agendar-novo'
      fullPath: '/admin/agendar-novo'
      preLoaderRoute: typeof AuthedAdminAgendarNovoRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/agendamentos': {
      id: '/_authed/admin/agendamentos'
      path: '/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AuthedAdminAgendamentosRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/agenda': {
      id: '/_authed/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AuthedAdminAgendaRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/equipe/': {
      id: '/_authed/admin/equipe/'
      path: '/'
      fullPath: '/admin/equipe/'
      preLoaderRoute: typeof AuthedAdminEquipeIndexRouteImport
      parentRoute: typeof AuthedAdminEquipeRoute
    }
    '/_authed/admin/equipe/$staffId/horarios': {
      id: '/_authed/admin/equipe/$staffId/horarios'
      path: '/$staffId/horarios'
      fullPath: '/admin/equipe/$staffId/horarios'
      preLoaderRoute: typeof AuthedAdminEquipeStaffIdHorariosRouteImport
      parentRoute: typeof AuthedAdminEquipeRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPrimeiroAcessoRoute: typeof AuthPrimeiroAcessoRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPrimeiroAcessoRoute: AuthPrimeiroAcessoRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthedAdminEquipeRouteChildren {
  AuthedAdminEquipeIndexRoute: typeof AuthedAdminEquipeIndexRoute
  AuthedAdminEquipeStaffIdHorariosRoute: typeof AuthedAdminEquipeStaffIdHorariosRoute
}

const AuthedAdminEquipeRouteChildren: AuthedAdminEquipeRouteChildren = {
  AuthedAdminEquipeIndexRoute: AuthedAdminEquipeIndexRoute,
  AuthedAdminEquipeStaffIdHorariosRoute: AuthedAdminEquipeStaffIdHorariosRoute,
}

const AuthedAdminEquipeRouteWithChildren =
  AuthedAdminEquipeRoute._addFileChildren(AuthedAdminEquipeRouteChildren)

interface AuthedAdminRouteRouteChildren {
  AuthedAdminAgendaRoute: typeof AuthedAdminAgendaRoute
  AuthedAdminAgendamentosRoute: typeof AuthedAdminAgendamentosRoute
  AuthedAdminAgendarNovoRoute: typeof AuthedAdminAgendarNovoRoute
  AuthedAdminClientesRoute: typeof AuthedAdminClientesRoute
  AuthedAdminCrmRoute: typeof AuthedAdminCrmRoute
  AuthedAdminEquipeRoute: typeof AuthedAdminEquipeRouteWithChildren
  AuthedAdminFinanceiroRoute: typeof AuthedAdminFinanceiroRoute
  AuthedAdminPdvRoute: typeof AuthedAdminPdvRoute
  AuthedAdminProdutosRoute: typeof AuthedAdminProdutosRoute
  AuthedAdminServicosRoute: typeof AuthedAdminServicosRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminAgendaRoute: AuthedAdminAgendaRoute,
  AuthedAdminAgendamentosRoute: AuthedAdminAgendamentosRoute,
  AuthedAdminAgendarNovoRoute: AuthedAdminAgendarNovoRoute,
  AuthedAdminClientesRoute: AuthedAdminClientesRoute,
  AuthedAdminCrmRoute: AuthedAdminCrmRoute,
  AuthedAdminEquipeRoute: AuthedAdminEquipeRouteWithChildren,
  AuthedAdminFinanceiroRoute: AuthedAdminFinanceiroRoute,
  AuthedAdminPdvRoute: AuthedAdminPdvRoute,
  AuthedAdminProdutosRoute: AuthedAdminProdutosRoute,
  AuthedAdminServicosRoute: AuthedAdminServicosRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
