/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminServicosRouteImport } from './routes/_authed/admin/servicos'
import { Route as AuthedAdminFinanceiroRouteImport } from './routes/_authed/admin/financeiro'
import { Route as AuthedAdminEquipeRouteImport } from './routes/_authed/admin/equipe'
import { Route as AuthedAdminClientesRouteImport } from './routes/_authed/admin/clientes'
import { Route as AuthedAdminAgendamentosRouteImport } from './routes/_authed/admin/agendamentos'
import { Route as AuthedAdminAgendaRouteImport } from './routes/_authed/admin/agenda'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminServicosRoute = AuthedAdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminFinanceiroRoute = AuthedAdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminEquipeRoute = AuthedAdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminClientesRoute = AuthedAdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAgendamentosRoute = AuthedAdminAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAgendaRoute = AuthedAdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/admin/agenda': typeof AuthedAdminAgendaRoute
  '/admin/agendamentos': typeof AuthedAdminAgendamentosRoute
  '/admin/clientes': typeof AuthedAdminClientesRoute
  '/admin/equipe': typeof AuthedAdminEquipeRoute
  '/admin/financeiro': typeof AuthedAdminFinanceiroRoute
  '/admin/servicos': typeof AuthedAdminServicosRoute
  '/admin/': typeof AuthedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agenda': typeof AuthedAdminAgendaRoute
  '/admin/agendamentos': typeof AuthedAdminAgendamentosRoute
  '/admin/clientes': typeof AuthedAdminClientesRoute
  '/admin/equipe': typeof AuthedAdminEquipeRoute
  '/admin/financeiro': typeof AuthedAdminFinanceiroRoute
  '/admin/servicos': typeof AuthedAdminServicosRoute
  '/admin': typeof AuthedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/admin/agenda': typeof AuthedAdminAgendaRoute
  '/_authed/admin/agendamentos': typeof AuthedAdminAgendamentosRoute
  '/_authed/admin/clientes': typeof AuthedAdminClientesRoute
  '/_authed/admin/equipe': typeof AuthedAdminEquipeRoute
  '/_authed/admin/financeiro': typeof AuthedAdminFinanceiroRoute
  '/_authed/admin/servicos': typeof AuthedAdminServicosRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/admin/agenda'
    | '/admin/agendamentos'
    | '/admin/clientes'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/servicos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/agenda'
    | '/admin/agendamentos'
    | '/admin/clientes'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/servicos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authed/admin'
    | '/_authed/admin/agenda'
    | '/_authed/admin/agendamentos'
    | '/_authed/admin/clientes'
    | '/_authed/admin/equipe'
    | '/_authed/admin/financeiro'
    | '/_authed/admin/servicos'
    | '/_authed/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/servicos': {
      id: '/_authed/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AuthedAdminServicosRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/financeiro': {
      id: '/_authed/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthedAdminFinanceiroRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/equipe': {
      id: '/_authed/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthedAdminEquipeRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/clientes': {
      id: '/_authed/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthedAdminClientesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/agendamentos': {
      id: '/_authed/admin/agendamentos'
      path: '/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AuthedAdminAgendamentosRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/agenda': {
      id: '/_authed/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AuthedAdminAgendaRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminAgendaRoute: typeof AuthedAdminAgendaRoute
  AuthedAdminAgendamentosRoute: typeof AuthedAdminAgendamentosRoute
  AuthedAdminClientesRoute: typeof AuthedAdminClientesRoute
  AuthedAdminEquipeRoute: typeof AuthedAdminEquipeRoute
  AuthedAdminFinanceiroRoute: typeof AuthedAdminFinanceiroRoute
  AuthedAdminServicosRoute: typeof AuthedAdminServicosRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminAgendaRoute: AuthedAdminAgendaRoute,
  AuthedAdminAgendamentosRoute: AuthedAdminAgendamentosRoute,
  AuthedAdminClientesRoute: AuthedAdminClientesRoute,
  AuthedAdminEquipeRoute: AuthedAdminEquipeRoute,
  AuthedAdminFinanceiroRoute: AuthedAdminFinanceiroRoute,
  AuthedAdminServicosRoute: AuthedAdminServicosRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
